service:
  name: func-helloworld

plugins:
  - serverless-google-cloudfunctions
provider:
  name: google
  runtime: go111
  project: tesidaviden
  credentials: ~/gcloud-keys/tesidaviden-209d19f52218.json
  region: europe-west1

functions:
  hello-world-function:
    handler: HelloHTTP
    events:
      - http: path
